### PR TITLE
build: start adopting bzlmod

### PR DESCRIPTION
**Pull request by jasonschroeder-sfdc**
Only four bazel dependencies were found in the existing bzlmod registry (https://registry.bazel.build/)

Fixes: https://github.com/bazelbuild/bazel-buildfarm/issues/1479

### CODE REVIEW

**Comment by jasonschroeder-sfdc** [comment]
Curiously, `//src/test/java/build/buildfarm/examples:tests` is failing 🤔

**Comment by werkt** [comment]
Will the [relevant issue](#1479) likely fixed when this is landed?

**Comment by jasonschroeder-sfdc** [comment]
Yes, we can link this PR to https://github.com/bazelbuild/bazel-buildfarm/issues/1479

**Review by werkt — APPROVED** [review]
Looks great, thanks for doing this legwork!

**Pull request merged**
