### PR TITLE
fix docs about CAS-`storages` 

### PR DESCRIPTION
**Pull request by Stunkymonkey**

### CODE REVIEW

**Comment by luxe** [comment]
Thanks @Stunkymonkey.  If you sign the CLA, I can land these fixes.

**Comment by Stunkymonkey** [comment]
@luxe I do not have the permission to retrigger the timed-out builds. The CLA is signed.

**Comment by werkt** [comment]
I restarted build, it is green now.

**Review by werkt — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
