### PR TITLE
add github action to package and publish the helm chart as a released artifact

### PR DESCRIPTION
**Pull request by andrewrothstein**
to publish releases with the gh cli please set
> Settings > Actions > General > Workflow Permissions > Read and Write Permissions

### CODE REVIEW

**Review by werkt — APPROVED** [review]
Looks good I suppose.

**Comment by andrewrothstein** [comment]
> to publish releases with the gh cli please set
> 
> > Settings > Actions > General > Workflow Permissions > Read and Write Permissions

Thanks for the consideration and merge.

Are you able to make this change? The github action that will publish the chart as a github release artifact on the next tag but it needs the authority do so. I'm guessing that authority hasn't been granted since I don't see any github release artifacts published previously.

**Comment by werkt** [comment]
Perms were already set like this before. Not sure how I should further verify the publish.

**Comment by andrewrothstein** [comment]
> Perms were already set like this before. Not sure how I should further verify the publish.

thanks! next tag should package and publish the chart. I did test this on my fork so I do believe it will work as expected. a thousand apologies if I've broken anything.

**Pull request merged**
