### PR TITLE
rename all BUILD files' name to BUILD.bazel

### PR DESCRIPTION
**Pull request by ddwolf**
Rename BUILD to BUILD.bazel and fix some errors followed.

[this](https://github.com/bazelbuild/bazel-buildfarm/compare/master...ddwolf:rename_BUILD_files?expand=1#diff-20ca8c7d9af5efe6a1cae9e9883f9151L9) is not referenced anywhere, so I removed it.

And this pr is related with this issue: #27

### CODE REVIEW

**Comment by ulfjack** [comment]
Why?

**Comment by ddwolf** [comment]
@ulfjack there are directories named "build" in lowercase and BUILD file in uppercase, they are treated as same objects in windows. And there is also this issue #27 .

**Comment by ulfjack** [comment]
Where are lowercase "build" directories?

**Comment by ddwolf** [comment]
@ulfjack in this directory: [src/main/protobuf/](https://github.com/bazelbuild/bazel-buildfarm/tree/master/src/main/protobuf)

**Comment by ulfjack** [comment]
I don't think #27 is worth fixing, but #28 may require having a BUILD.bazel file?

**Comment by ddwolf** [comment]
well this could be closed for #28 has been fixed. And not all BUILD files have to be renamed, by ulfjack's suggest.

**Pull request closed without merging**
