### PR TITLE
shardworker: add HealthStatusManager

### PR DESCRIPTION
**Pull request by dhaivat**
use same implementation as BuildFarmServer in #291

### CODE REVIEW

**Comment by dhaivat** [comment]
Hello @werkt and @luxe - I've added HealthStatusManager to shard worker similar to what is present in BuildFarmServer, thank you.

**Comment by luxe** [comment]
thanks @dhaivat!  

It makes sense to me.  I haven't actually queried grpc health before.  
@80degreeswest, @jacobmou, any thoughts?

**Comment by dhaivat** [comment]
np! @luxe, @80degreeswest, @jacobmou for more context, I've essentially copied everything @werkt did for BuildFarmServer in #291

**Review by 80degreeswest — APPROVED** [review]
LGTM

**Pull request merged**
