### PR TITLE
Add details regarding jedis fork

### LINKED ISSUE #664: Kindly document the Jedis fork
Buildfarm is using a Jedis fork, rather than [some official release of Jedis](https://github.com/redis/jedis/releases):

<https://github.com/bazelbuild/bazel-buildfarm/blob/2b7c7d420f91e25af80afccb1c18343dc22596a3/deps.bzl#L89-L96>

Could you please add comments in the code above describing the reason for using this fork?

# Background

The reason I'm asking is that we have made [a Jedis PR](https://github.com/redis/jedis/pull/2358) for backing off on cluster connection failures.

At some point, we'd like for Buildfarm to start using a Jedis version with backoff enabled.

And as long as Buildfarm uses a fork of Jedis, it's hard for us to know what a Jedis version bump would require.

### PR DESCRIPTION
**Pull request by werkt**
Fixes #664

### CODE REVIEW

**Comment by luxe** [comment]
I'm guessing walles wants to upgrade redis for upstream fixes.  Maybe we can contribute your fork back to upstream as well?

**Review by luxe — APPROVED** [review]

**Comment by werkt** [comment]
> I'm guessing walles wants to upgrade redis for upstream fixes. Maybe we can contribute your fork back to upstream as well?

Possibly, but the cluster pipelining thing was requested a while ago and rejected. I could pursue some of them, but I'm guessing nobody is going to be interested in the slf4j removal.

**Comment by walles** [comment]
> I'm guessing nobody is going to be interested in the slf4j removal.

Instead of removing SLF4J from Jedis, Buildfarm should just add `slf4j-jdk14.jar` to its classpath:
<http://www.slf4j.org/faq.html#where_is_binding>

**Comment by werkt** [comment]
> > I'm guessing nobody is going to be interested in the slf4j removal.
> 
> Instead of removing SLF4J from Jedis, Buildfarm should just add `slf4j-jdk14.jar` to its classpath:
> http://www.slf4j.org/faq.html#where_is_binding

That was what we were trying to avoid... also, we don't appear to be at a minimum of java14 everywhere (macos).

Random logging endpoints introduced by dependencies causes difficult to bound messaging.

**Comment by walles** [comment]
> That was what we were trying to avoid... also, we don't appear to be at a minimum of java14 everywhere (macos).

The `jdk14` part of `slf4j-jdk14.jar` refers to "Java 1.4", which is where Java Logging was introduced.

Yay for version numbering schemes :)

**Pull request merged**
