### PR TITLE
update container up time

### PR DESCRIPTION
**Pull request by jiaquan1**
https://jira.int.aurora.tech/browse/AV-88329

### CODE REVIEW

**Comment by luxe** [comment]
yay, new contributor! plz post the contents of the jira ticket here since this a public project. added @80degreeswest for your review.

**Comment by jiaquan1** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Comment by jiaquan1** [comment]
@googlebot I fixed it.

**Comment by jiaquan1** [comment]
@googlebot I fixed it.

**Comment by jiaquan1** [comment]
@googlebot I fixed it.

**Pull request closed without merging**
