### PR TITLE
Update ingress.yaml

### PR DESCRIPTION
**Pull request by alexiscarbillet**
Hello,

I am adding "-server" in the pathType. It is needed for the ingress to work

### CODE REVIEW

**Comment by andrewrothstein** [comment]
Not sure I follow. The pathType is one of ImplementationSpecific, Exact, or Prefix. The value is set by the user in the applied Values when u enable Ingress.
https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types

**Comment by alexiscarbillet** [comment]
Hello, 

Sorry I changed the wrong line at first, I just committed again.
I added more information for my case:

server:
  ingress:
    enabled: true
    hosts:
      - host: bazel.com
        paths:
          - path: /
            pathType: ImplementationSpecific

For the ingress, I get this error
│ Rules:                                                                                                                                                                                         │
│   Host                                         Path  Backends                                                                                                                                  │
│   ----                                         ----  --------                                                                                                                                  │
│   bazel.com                                                                                                                                                 │
│                                                /   bazel-buildfarm:8980 (<error: endpoints "bazel-buildfarm" not found>)                                                                       │
│ Annotations:                                   meta.helm.sh/release-name: bazel-buildfarm                                                                                                      │
│                                                meta.helm.sh/release-namespace: bazel-buildfarm

while the service created is named:
│ Name:              bazel-buildfarm-server                                                                                                                                                      │
│ Namespace:         bazel-buildfarm                                                                                                                                                             │

I tried with pathType: Prefix but I have the same error.
However with the patch it works

**Comment by andrewrothstein** [comment]
please rebase

**Comment by werkt** [comment]
@andrewrothstein can you review since push?

**Comment by andrewrothstein** [comment]
LGTM

**Pull request merged**
