### PR TITLE
feat: support --redis_uri command line option

### PR DESCRIPTION
**Pull request by jasonschroeder-sfdc**
Support a `--redis_uri` command line option for start-up.

**TODO:** I wasn't sure where to document it under `_site`? Please let me know if it needs to be in the doc site. Thanks!

Partially addresses #1445

### CODE REVIEW

**Comment by werkt** [comment]
Documenting this could take the form of another column under https://github.com/bazelbuild/bazel-buildfarm/blob/main/_site/docs/configuration/configuration.md that lists cmdline arg aliases for a config.

**Comment by werkt** [comment]
@jasonschroeder-sfdc did you want to circle back on the docs here, or are you punting for later changes?

**Comment by jasonschroeder-sfdc** [comment]
@werkt sorry - the ol' day job is killing me with deadlines. I'll squeeze these out today.

**Comment by jasonschroeder-sfdc** [comment]
Also, is URI or URL the correct term for this? 🤔

**Comment by werkt** [comment]
> Also, is URI or URL the correct term for this? 🤔

It is whatever the mechanism we use to interpret it says it is: in this case we're using java.net.URI. As long as nobody changes that, or looks too closely at whether it's the correct usage, itsa URI.

**Review by werkt — APPROVED** [review]
Looks good, thanks for the typo cleanups

**Pull request merged**
