### PR TITLE
Resolve all Redis cluster hosts on startup

### PR DESCRIPTION
**Pull request by thna123459**
Redis cluster instances may not be all behind a single load balancer;
when a Redis instance disappears or times out, the worker can be unable
to recover:

2020-11-06T14:30:26.000+00:00 x.y.z.t shard-worker:5622936216666112:8b7c9a88ef795687b74f30ef68aa8adf6bf5b9cc[22492]: redis.clients.jedis.exceptions.JedisClusterMaxAttemptsException: No more cluster attempts left.
2020-11-06T14:30:26.000+00:00 x.y.z.t shard-worker:5622936216666112:8b7c9a88ef795687b74f30ef68aa8adf6bf5b9cc[22492]: redis.clients.jedis.exceptions.JedisClusterMaxAttemptsException: No more cluster attempts left.
2020-11-06T14:30:27.000+00:00 x.y.z.t shard-worker:5622936216666112:8b7c9a88ef795687b74f30ef68aa8adf6bf5b9cc[22492]: redis.clients.jedis.exceptions.JedisClusterMaxAttemptsException: No more cluster attempts left.
2020-11-06T14:30:27.000+00:00 x.y.z.t shard-worker:5622936216666112:8b7c9a88ef795687b74f30ef68aa8adf6bf5b9cc[22492]: redis.clients.jedis.exceptions.JedisClusterMaxAttemptsException: No more cluster attempts left.

### CODE REVIEW

**Review by luxe — APPROVED** [review]
This makes sense to me.  I'll wait for @werkt to also review.

**Comment by werkt** [comment]
I'm not sure I understand what's going on here - you're doing a DNS resolve on the hostname specified, and that makes things *more* reliable? Generally I don't like introducing resolutions at this level, and it doesn't afford the truly useful behavior, which might be to specify say all the hosts in a cluster (you might do that with a repeated redis_uri field).

Can you explain why using the IP address, but not the DNS name, is capable of making things more reliable? This also doesn't affect what members of a cluster get resolved anyway, which is accomplished internal to jedis in the clustered client implementation's discovery with `cluster slots`, which provides all endpoint information used during actual commands.

If you're saying that jedis is non-resilient to cluster failovers, I'll definitely buy that, but this isn't the place for the fix of that.

**Comment by thna123459** [comment]
Can we have a repeated `redis_uri field`? the configuration only allows for a single one at this time:
https://github.com/bazelbuild/bazel-buildfarm/blob/master/examples/shard-worker.config.example#L126

We have a cluster of 6 Redis instances (3 replicas). We rarely rotate them and the cluster state never turns red, yet we are observing random timeouts even when the workers are (mostly) idle (`Caused by: java.net.SocketTimeoutException: Read timed out`). We have not tried [tuning the timeout values at this point](https://github.com/redis/jedis/wiki/FAQ#if-you-get-javanetsockettimeoutexception-read-timed-out-exception) yet, and the source code sets a limit of 2000ms ([is there any example?](https://github.com/bazelbuild/bazel-buildfarm/blob/master/examples/shard-worker.config.example))

```
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]: Nov 13, 2020 9:50:45 PM build.buildfarm.cas.CASFileCache completeWrite
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]: SEVERE: error during write completion onPut for 6029efe9a2c638a5939ddf4fe24603e0b6774c69994f727cc7e4a13dc74d7335/130
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]: redis.clients.jedis.exceptions.JedisClusterMaxAttemptsException: No more cluster attempts left.
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:27)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at redis.clients.jedis.JedisCluster.sadd(JedisCluster.java:707)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.instance.shard.RedisShardBackplane.lambda$addBlobLocation$18(RedisShardBackplane.java:863)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.common.redis.RedisClient$1.run(RedisClient.java:88)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.common.redis.RedisClient$1.run(RedisClient.java:85)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.common.redis.RedisClient.call(RedisClient.java:118)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.common.redis.RedisClient.run(RedisClient.java:84)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.instance.shard.RedisShardBackplane.addBlobLocation(RedisShardBackplane.java:861)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.worker.shard.Worker.onStoragePut(Worker.java:700)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.cas.CASFileCache.completeWrite(CASFileCache.java:668)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.cas.CASFileCache.lambda$newOutput$7(CASFileCache.java:1103)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.cas.CASFileCache$9.commit(CASFileCache.java:2794)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.cas.CASFileCache$9.close(CASFileCache.java:2735)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.cas.CASFileCache$8.withSingleTermination(CASFileCache.java:2476)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.cas.CASFileCache$8.close(CASFileCache.java:2470)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.cas.CASFileCache$6.close(CASFileCache.java:1167)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.server.WriteStreamObserver.close(WriteStreamObserver.java:339)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.server.WriteStreamObserver.handleWrite(WriteStreamObserver.java:331)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.server.WriteStreamObserver.handleRequest(WriteStreamObserver.java:284)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.server.WriteStreamObserver.initialize(WriteStreamObserver.java:227)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.server.WriteStreamObserver.onUncommittedNext(WriteStreamObserver.java:113)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.server.WriteStreamObserver.onNext(WriteStreamObserver.java:93)
2020-11-13T21:50:45.000+00:00 10.173.28.198 worker:6352036801675264:24695ac2c46146c35c41b4210354d4184738ea27[22896]:  at build.buildfarm.server.WriteStreamObserver.onNext(WriteStreamObserver.java:53)
```

The following is my interpretation which may well be incorrect:

When a timeout occurs, a `JedisClusterMaxAttemptsException` and be thrown and then the worker process will restart. When this happens, the same worker will load the cache and send even more requests to the same Redis instance. The additional load to the same host may cause new read timeouts and initiate a restart loop.

We can close this pull request, but at least please tell us more about the multiple`redis_uri` and the timeout-in-worker-config approaches.

**Comment by thna123459** [comment]
[Redis timeout settings](https://github.com/bazelbuild/bazel-buildfarm/pull/604) make this unnecessary.

**Pull request closed without merging**
