### PR TITLE
[bug] [experiment] existing entry did not appear fix

### PR DESCRIPTION
**Pull request by luxe**
Continued investigation #1295
I'm still getting "existing entry did not appear" exceptions.  
What would happen if we did this instead?

### CODE REVIEW

**Comment by jerrymarino** [comment]
I'm still hitting this from time to time, in one instance I'm seeing an expiry right before the exception
```
2023-05-03T09:58:47.893-07:00   INFO: expired key 04efd0f6728c7bb562a3d4b5cc4b26d56406d723b6fd9d5f9a24348f0a7a7b4b_exec
```

Then a few milli seconds later:
```
2023-05-03T09:58:48.901-07:00 build.buildfarm.worker.shard.CFCExecFileSystem$ExecDirException: /tmp/worker/shard/operations/c2d0cceb-07d9-4486-9c33-a5c72f9acba2: 1 exceptions: [build.buildfarm.cas.cfc.CASFileCache$PutDirectoryException: /tmp/worker/cache/b565d9c3a698afe4130eb9f4d0e1d403daf789ef2fa7f605c14375ccb00371d1_dir: 1 exceptions: [java.util.concurrent.ExecutionException: java.io.IOException: existing entry did not appear for 04efd0f6728c7bb562a3d4b5cc4b26d56406d723b6fd9d5f9a24348f0a7a7b4b_exec]]
	at build.buildfarm.worker.shard.CFCExecFileSystem.checkExecErrors(CFCExecFileSystem.java:322)
	at build.buildfarm.worker.shard.CFCExecFileSystem.createExecDir(CFCExecFileSystem.java:414)
	at build.buildfarm.worker.shard.ShardWorkerContext.createExecDir(ShardWorkerContext.java:712)
	at build.buildfarm.worker.InputFetcher.fetchPolled(InputFetcher.java:193)
	at build.buildfarm.worker.InputFetcher.runInterruptibly(InputFetcher.java:103)
	at build.buildfarm.worker.InputFetcher.run(InputFetcher.java:282)
	at java.base/java.lang.Thread.run(Thread.java:1623)
	Suppressed: build.buildfarm.cas.cfc.CASFileCache$PutDirectoryException: /tmp/worker/cache/b565d9c3a698afe4130eb9f4d0e1d403daf789ef2fa7f605c14375ccb00371d1_dir: 1 exceptions: [java.util.concurrent.ExecutionException: java.io.IOException: existing entry did not appear for 04efd0f6728c7bb562a3d4b5cc4b26d56406d723b6fd9d5f9a24348f0a7a7b4b_exec]
		at build.buildfarm.cas.cfc.CASFileCache.lambda$putDirectorySynchronized$20(CASFileCache.java:2286)
		at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:221)
		at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:208)
		at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:122)
		at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
		Suppressed: java.util.concurrent.ExecutionException: java.io.IOException: existing entry did not appear for 04efd0f6728c7bb562a3d4b5cc4b26d56406d723b6fd9d5f9a24348f0a7a7b4b_exec
			at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
			at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
			at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
			at build.buildfarm.cas.cfc.CASFileCache.lambda$putDirectorySynchronized$20(CASFileCache.java:2277)
			... 9 more
		Caused by: java.io.IOException: existing entry did not appear for 04efd0f6728c7bb562a3d4b5cc4b26d56406d723b6fd9d5f9a24348f0a7a7b4b_exec
			at build.buildfarm.cas.cfc.CASFileCache$8.commit(CASFileCache.java:2900)
			at build.buildfarm.cas.cfc.CASFileCache$8.close(CASFileCache.java:2852)
			at build.buildfarm.cas.cfc.CASFileCache$7.withSingleTermination(CASFileCache.java:2515)
			at build.buildfarm.cas.cfc.CASFileCache$7.close(CASFileCache.java:2509)
			at build.buildfarm.cas.cfc.CASFileCache.putAndCopy(CASFileCache.java:2399)
			at build.buildfarm.cas.cfc.CASFileCache.lambda$put$25(CASFileCache.java:2373)
			... 9 more
```


I'm going to try and test this a bit more and potentially bump reference counts before we call `putIfAbsent`
https://github.com/bazelbuild/bazel-buildfarm/blob/main/src/main/java/build/buildfarm/cas/cfc/CASFileCache.java#L2877

Something like:
```
        boolean inserted = false;
        try {
              // Bumping references prior to getting an antry
              referenceIfExists(key);

              Files.createLink(CASFileCache.this.getPath(key), writePath);
              existingEntry = storage.putIfAbsent(key, entry);
              inserted = existingEntry == null;
          }
          
          // returns null because it was legitimately evicted 
          existingEntry = storage.get(key);
```

**Comment by werkt** [comment]
I dont agree with the fix, but that is a fantastic smoking gun you've got there @jerrymarino that indicates that we are racing the expiration, which is not doing things consistently enough for our purpose here. I'll have a good look at ensuring we can safely expire and populate at the same time.

Quick fix though - this looks like your CFC is likely way undersized for your working set of inputs. Getting more filesystem space for it may alleviate the pressure to evict below the input high water mark.

**Comment by jerrymarino** [comment]
Thanks @werkt ! I'm going to see if I can provide other evidence for this, I've some decent evidence that points to we're somehow evicting during execution: perhaps getting `FINE` logging just in this file may help too. 

Also consider what the state of the world looks like _if_ we're contended on `ConcurrentMap<String, Entry> storage` access. In my case, I've got a situation where it's executing actions with relatively large outputs and inputs and CAS is maxed out in size unfortunately: this puts some serious load on the locking / ref counting.

Other fixes I've been kicking the tires of ensure input eviction doesn't during execution: assuming the the material in the exception was valid on disk at one point and therefore evicted. I'm curious to know your suggestion for a fix - getting CAS to perform here is pretty pivotal to me; getting a testable repro is TBD and this only happens in the production load.

**Comment by werkt** [comment]
@jerrymarino Please take a look at this tree: https://github.com/werkt/bazel-buildfarm/tree/expire-commit-race

This is a quickly constructed exclusivity for expire and entry creation that is very likely to prevent the did not appear race unexpectedly. Theory is sound, but needs a field run.

Regardless: The overall load is not what concerns me: if your expirations are having *anything* to do with your action input directories, your local cache storage is too small. The proof of this is quite simply, from empty, to your max size, how much time elapses for a fresh worker? If it isn't multiple hours (or it's obscured by slow network/disk), then you're at great risk of having these grinding wheels lock. I want you to see if 10x-ing your storage solves the problem unto itself.

**Comment by jerrymarino** [comment]
@werkt thanks for writing this up 👍 . Pulling it down right now and digging through it a bit over the next couple days, I had 1-2 questions on the commit if you have a min 

> how much time elapses for a fresh worker

CAS runaway evaporates _very_ fast - for t-shirt size of "high" throughput I have some that burned ~50% of a CAS in ~45 mins. These are exotic machines with unavoidable small disks super glued to the logic board and mini cases that run some massive artifacts ( alongside of a number of symlinks ). Still it's beneficial to have some form of an LRU on them.. 

I'm going to try and come up with some form of tests to try and capture: perhaps I can get it to exibit my issues with a unit test.

**Comment by jerrymarino** [comment]
In the last 4 days, 100% of the instances of `existing entry did not appear for XX` e.gl:
```
java.io.IOException: existing entry did not appear for e14c1ad0388f864520d88bcc06e2b3ee6efa34dc53758390fc9238ea1ae772cf_exec
```
All retain the suffix `_exec` and all end up having an `expired key` log leading up to seconds of it popping:
```
INFO: expired key e14c1ad0388f864520d88bcc06e2b3ee6efa34dc53758390fc9238ea1ae772cf_exec
```

Further:
- average `input_fetch_time_ms` sits around `6000-7000ms`
- average `input_fetch_still_time_ms` sits around `5000-6000ms` ms - and on average is `1000ms` below `input_fetch_time_ms`

**Comment by jerrymarino** [comment]
Also:
- I see them stable _around_ the `maxSizeBytes` for a few hours and sometimes a few days prior to raising this

**Comment by jerrymarino** [comment]
### Entire log leading up to the event:
```
2023-05-08T13:24:14.919-07:00	INFO: expired key e117dbe1e20e767e9a0a1615e8059b642b63f12199e105185a343315dd83833c_exec
2023-05-08T13:24:14.919-07:00	May 08, 2023 1:24:14 PM build.buildfarm.cas.cfc.CASFileCache lambda$charge$28
2023-05-08T13:24:14.919-07:00	INFO: expired key 9b7f8c404712095cfdf2d3bfb848455a28a44661ddab0aa5f43f282108b74eae_exec
2023-05-08T13:24:14.919-07:00	May 08, 2023 1:24:14 PM build.buildfarm.cas.cfc.CASFileCache lambda$charge$28
2023-05-08T13:24:14.919-07:00	INFO: expired key 854ba9c5b36e5db5973346054431169ded9bd745c46f3bb1ae4624b3a658f33e_exec
2023-05-08T13:24:14.919-07:00	May 08, 2023 1:24:14 PM build.buildfarm.cas.cfc.CASFileCache lambda$charge$28
2023-05-08T13:24:14.919-07:00	INFO: expired key 09988c123a4e07b95c4f97825c1b47780bb39f0a89571004f11599c2c07101e0_exec
2023-05-08T13:24:14.919-07:00	May 08, 2023 1:24:14 PM build.buildfarm.cas.cfc.CASFileCache lambda$charge$28
2023-05-08T13:24:14.919-07:00	INFO: expired key 6b352f5a882ae79042bd0c4246a17a5e982df99716a8ef5f182ca047d70d997b_exec
2023-05-08T13:24:14.919-07:00	May 08, 2023 1:24:14 PM build.buildfarm.cas.cfc.CASFileCache lambda$charge$28
2023-05-08T13:24:14.919-07:00	INFO: expired key 190d8285732e4222f5a26978d40df711fa242d31d1d1ea9888b03349a8c4257b_exec
2023-05-08T13:24:14.919-07:00	May 08, 2023 1:24:14 PM build.buildfarm.cas.cfc.CASFileCache lambda$charge$28
2023-05-08T13:24:14.919-07:00	INFO: expired key fb641b5b21e94b4b838f16f5a1d79759b63583648d1d8316941ceb3440a29534_exec
2023-05-08T13:24:14.919-07:00	May 08, 2023 1:24:14 PM build.buildfarm.cas.cfc.CASFileCache lambda$charge$28
2023-05-08T13:24:14.919-07:00	INFO: expired key 66bd6e89d66456f6c023356fc2f28b1df610c11f1be7cd7f7698ef862cf389b6_exec
2023-05-08T13:24:14.919-07:00	May 08, 2023 1:24:14 PM build.buildfarm.cas.cfc.CASFileCache lambda$charge$28
2023-05-08T13:24:15.671-07:00	INFO: expired key ab57b7ae851a6fdd87fcb244055b688ef9871d1479bdeee381920205929f8de4_exec
2023-05-08T13:24:15.671-07:00	May 08, 2023 1:24:15 PM build.buildfarm.cas.cfc.CASFileCache lambda$charge$28
2023-05-08T13:24:15.671-07:00	INFO: expired key 276b1363bfc4a831de1fc2926e8f0771704a3ca356419851282f756245aa9f45_exec
2023-05-08T13:24:15.671-07:00	May 08, 2023 1:24:15 PM build.buildfarm.worker.shard.ShardWorkerContext lambda$resumePoller$1
2023-05-08T13:24:15.671-07:00	INFO: InputFetcher: poller: Completed Poll for shard/operations/bdd6d98f-9989-42b7-9106-7b84f341d32f: OK
2023-05-08T13:24:15.671-07:00	May 08, 2023 1:24:15 PM build.buildfarm.worker.shard.ShardWorkerContext lambda$resumePoller$1
2023-05-08T13:24:16.675-07:00	INFO: Executor: poller: Completed Poll for shard/operations/40524e41-1ace-4e5f-ab07-f55f0ca23d91: OK
2023-05-08T13:24:16.675-07:00	May 08, 2023 1:24:16 PM build.buildfarm.worker.InputFetcher fetchPolled
2023-05-08T13:24:16.675-07:00	SEVERE: error creating exec dir for shard/operations/bdd6d98f-9989-42b7-9106-7b84f341d32f
```

### Sample of `InputFetcher` search query 
```
2023-05-08T13:23:44.981-07:00	INFO: InputFetcher(claim): poller: Completed Poll for shard/operations/40524e41-1ace-4e5f-ab07-f55f0ca23d91: OK
2023-05-08T13:23:49.763-07:00	INFO: InputFetcher(claim): poller: Completed Poll for shard/operations/e886f5bc-0ef3-45df-bfe3-775d4e434a13: OK
2023-05-08T13:23:50.771-07:00	INFO: InputFetcher(claim): poller: Completed Poll for shard/operations/e886f5bc-0ef3-45df-bfe3-775d4e434a13: OK
2023-05-08T13:24:15.671-07:00	INFO: InputFetcher: poller: Completed Poll for shard/operations/bdd6d98f-9989-42b7-9106-7b84f341d32f: OK
2023-05-08T13:24:16.675-07:00	May 08, 2023 1:24:16 PM build.buildfarm.worker.InputFetcher fetchPolled
2023-05-08T13:24:16.675-07:00	build.buildfarm.worker.shard.CFCExecFileSystem$ExecDirException: /tmp/worker/shard/operations/bdd6d98f-9989-42b7-9106-7b84f341d32f: 1 exceptions: 
```

**Comment by jerrymarino** [comment]
Also it looks like I see some instances where it's for whatever-reason attempting to continuously expire the same key, it eventually lead to this exception 
```
2023-05-18T00:53:09.691-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T00:53:52.784-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T01:14:41.917-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T01:25:11.519-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T01:35:21.624-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T02:04:41.375-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T02:23:28.691-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T02:26:58.686-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T02:31:41.216-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T02:45:16.497-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T03:35:13.043-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T03:44:28.487-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T04:09:45.877-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T04:22:19.075-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T04:32:35.890-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T04:54:30.983-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T05:06:18.611-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T05:09:48.070-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T05:11:40.484-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T05:12:00.549-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T05:31:56.386-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
2023-05-18T05:32:03.464-07:00	build.buildfarm.worker.shard.CFCExecFileSystem$ExecDirException: /tmp/worker/shard/operations/dcafcca2-1944-4562-ac5c-9c2432a0384f: 1 exceptions: [build.buildfarm.cas.cfc.CASFileCache$PutDirectoryException: /tmp/worker/cache/2fa1b9c710ad482ffa8f252fac6ff43858c5de20a54d2706ac9c34e5c25728a6_dir: 1 exceptions: [java.util.concurrent.ExecutionException: java.io.IOException: existing entry did not appear for 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec]] at build.buildfarm.worker.shard.CFCExecFileSystem.checkExecErrors(CFCExecFileSystem.java:322) at build.buildfarm.worker.shard.CFCExecFileSystem.createExecDir(CFCExecFileSystem.java:414) at build.buildfarm.worker.shard.ShardWorkerContext.createExecDir(ShardWorkerContext.java:712) at build.buildfarm.worker.InputFetcher.fetchPolled(InputFetcher.java:193) at build.buildfarm.worker.InputFetcher.runInterruptibly(InputFetcher.java:103) at build.buildfarm.worker.InputFetcher.run(InputFetcher.java:282) at java.base/java.lang.Thread.run(Thread.java:1623) Suppressed: build.buildfarm.cas.cfc.CASFileCache$PutDirectoryException: /tmp/worker/cache/2fa1b9c710ad482ffa8f252fac6ff43858c5de20a54d2706ac9c34e5c25728a6_dir: 1 exceptions: [java.util.concurrent.ExecutionException: java.io.IOException: existing entry did not appear for 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec] at build.buildfarm.cas.cfc.CASFileCache.lambda$putDirectorySynchronized$20(CASFileCache.java:2286) at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:221) at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:208) at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:122) at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) Suppressed: java.util.concurrent.ExecutionException: java.io.IOException: existing entry did not appear for 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588) at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547) at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91) at build.buildfarm.cas.cfc.CASFileCache.lambda$putDirectorySynchronized$20(CASFileCache.java:2277) ... 9 more Caused by: java.io.IOException: existing entry did not appear for 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec at build.buildfarm.cas.cfc.CASFileCache$8.commit(CASFileCache.java:2900) at build.buildfarm.cas.cfc.CASFileCache$8.close(CASFileCache.java:2852) at build.buildfarm.cas.cfc.CASFileCache$7.withSingleTermination(CASFileCache.java:2515) at build.buildfarm.cas.cfc.CASFileCache$7.close(CASFileCache.java:2509) at build.buildfarm.cas.cfc.CASFileCache.putAndCopy(CASFileCache.java:2399) at build.buildfarm.cas.cfc.CASFileCache.lambda$put$25(CASFileCache.java:2373) ... 9 more
2023-05-18T05:36:56.239-07:00	INFO: expired key 1dc5fe30d6c7a26abd7761f0613075d3584885db0299f45c19ac2d27e69c0568_exec
```

**Comment by jerrymarino** [comment]
I've had a number of issues with `createExecDir` that I've distilled down into this PR https://github.com/bazelbuild/bazel-buildfarm/pull/1353/files . The largest being mutation of content and expiration while building

**Pull request closed without merging**
