### PR TITLE
feat: Redis password from file

### PR DESCRIPTION
**Pull request by jasonschroeder-sfdc**
Support reading the Redis password from:
- the Redis URL (in a format like `redis://username:password@host`, or `redis://:password@host`
- the `redisCredentialFile` from the config YAML. This could be a Kubernetes secret or Hashicorp Vault or whatever. Just a file with a secret inside.

### CODE REVIEW

**Review by werkt — APPROVED** [review]
Given the prioritization, I assume that there's some change to the documentation that this would merit. Change looks fine overall, I don't think it would break any password-less redis situations inadvertently.

**Comment by jasonschroeder-sfdc** [comment]
Thank you @werkt ! Doc change coming up...

**Comment by werkt** [comment]
Do you want me to wait to merge this for doc changes in this commit, or will you be doing those separately?

**Comment by jasonschroeder-sfdc** [comment]
Please wait - I'll add it to this PR. Thanks for checking!

**Comment by werkt** [comment]
Seems a bit odd that the password file should take precedence over the immediately declared redisPassword field, but OK, as long as it's documented.

**Review by werkt — APPROVED** [review]

**Pull request merged**
