### PR TITLE
Extract all url path handling code to new UrlPath class

### PR DESCRIPTION
**Pull request by abergmeier-dsfishlabs**
Remove is* methods since implementation is inefficient and repetitive.
Instead introduce a UrlPath.detectServiceType, which is only a bit inefficient.

### CODE REVIEW

**Comment by abergmeier-dsfishlabs** [comment]
@hhclam You want to review?

**Comment by hhclam** [comment]
LGTM.

**Comment by abergmeier** [comment]
Personally I used a `enum` because this should be fairly easy for the VM to inline. With an interface I am somewhat sceptical on that. If we do not care about perf I'll make the change.

**Comment by abergmeier-dsfishlabs** [comment]
@werkt I think `UrlPath.ResourceOperation` should be fine now. Looking at its usage, I do not see the benefit of introducing more object orientation.
Regardless I think you can introduce a package level `ResourceOperation` interface just fine and have all Url handling be in `UrlPath`. I think that would make sense anyway. But that is then probably best introduced by you on top of this PR.

**Pull request merged**
