### PR TITLE
[ci] extend formatter to support protobuf

### PR DESCRIPTION
**Pull request by luxe**
protobuf files can be formatted with `clang-format`.  We extend `format.sh` to support this.  The gate is currently turned off.  We can turn it on later; I didn't wanted to format all of the protobuf files as part of the integration.

### CODE REVIEW

**Review by werkt — COMMENTED** [review]
So the only way we can get a proto formatter is with clang-format, and we have to incorporate the entirety of an llvm_toolchain to do it? Seems pretty heavy handed...

**Comment by luxe** [comment]
> So the only way we can get a proto formatter is with clang-format, and we have to incorporate the entirety of an llvm_toolchain to do it? Seems pretty heavy handed...

agreed.  I wish llvm hosted clang-format individually.  this seems to be what buildbarn is doing as well:
https://github.com/buildbarn/bb-remote-execution/runs/3243994208#step:8:1

**Review by werkt — APPROVED** [review]
This is fine for now, but really, I'd rather we host/point to clang-format as an architecture dependent binary somewhere and use that. We don't want to depend upon anything but released versions, and I'd prefer we not be in the business of building this.

**Comment by luxe** [comment]
sounds good.  For now, the formatter skips using this.  bazel won't fetch it since no target depends on it.  We'll look for something more lightweight.

**Pull request merged**
