### PR TITLE
[metrics] Changing summary metrics to histogram in prometheus clients

### PR DESCRIPTION
**Pull request by rijosimon**
This change updates the following summary metrics to instead report as histograms:

io_bytes_read
missing_blobs
io_bytes_write
execution_time_ms
execution_stall_time_ms
input_fetch_time_ms
input_fetch_stall_time_ms

This change will make these metrics aggregatable across servers and workers allowing easier tracking in dashboards and alerting mechanisms.

This change resolves the following issue: https://github.com/bazelbuild/bazel-buildfarm/issues/868

### CODE REVIEW

**Comment by rijosimon** [comment]
@googlebot I signed it!

**Review by luxe — APPROVED** [review]

**Comment by luxe** [comment]
@80degreeswest we'll wait for your approval.  you may need to adjust your own dashboards.  In regards to any performance concerns, histograms should perform better.  See comparison chart: https://prometheus.io/docs/practices/histograms/#quantiles

**Review by 80degreeswest — APPROVED** [review]
TODO: Wiki will need to be updated here: https://github.com/bazelbuild/bazel-buildfarm/wiki/Metrics

**Comment by rijosimon** [comment]
@googlebot I consent

**Comment by rijosimon** [comment]
@googlebot I signed it!

**Pull request merged**
